### ISSUE TITLE
FR: custom ssid name

### ISSUE THREAD

**Issue by xiv3r** [BlackTechX011/DeautherX_Web_Tools#1]

**Comment by BlackTechX011** [comment]
# @xiv3r xiv3r 
can u explain what do u mean

**Comment by BlackTechX011** [comment]
soon i will update the tool

**Comment by BlackTechX011** [comment]
u want to change DeautherX ssid name ?
know more about https://github.com/BlackTechX011/DeautherX/wiki/serial‐commands
