### ISSUE TITLE
Dstrike deaither mini

### ISSUE THREAD

**Issue by ju5t3nc4s3** [BlackTechX011/DeautherX_Web_Tools#2]
just tryed ur web tool and the 1.3 display for the ofifcial dstike deauther mini , disply not working..  SH1106_I2C
in the A_config.h u have it set as  SSD1306_I2C
// ===== DISPLAY ===== //
//  #define SH1106_I2C
 #define SSD1306_I2C

**Comment by BlackTechX011** [comment]
for dstike boads or anything else u need to use Arduino ide for flashing

**Comment by BlackTechX011** [comment]
## Setup with I2C OLED

| Display | GPIO |
| ------- | ---- |
| GND | GND |
| VCC/VDD | VCC / 3.3V |
| SCL/CLK/SCK | GPIO 4 (D2) |
| SDA | GPIO 5 (D1) |

| Button | GPIO |
| ------ | ---- |
| UP | GPIO 14 (D5) |
| Down | GPIO 12 (D6) |
| A | GPIO 13 (D7) |
| B | GPIO 2 (D4) |

| NEOPIXEL LED | GPIO |
| ------ | ---- |
| GND | GND |
| VCC | VCC/3.3V |
| DIN | GPIO 15 (D8) |

| Light | GPIO |
| ------ | ---- |
| GND | GND |
| VCC | GPIO 16 (D0) |

**Comment by BlackTechX011** [comment]
.
